package domain.conversation

enum class ConversationStep {
    ASK_TOTAL_AMOUNT,
    ASK_TAX,
    ASK_TIP_MODE,
    ASK_TIP_VALUE,
    ASK_SPLIT_MODE,
    ASK_PEOPLE_COUNT,

    ASK_MENU_ITEMS,
    ASK_MENU_PARTICIPANTS,
    ASK_MENU_ASSIGNMENTS,

    ASK_EXCHANGE_RATE_MODE,
    ASK_EXCHANGE_RATE_VALUE,

    SHOW_RESULT,
    RESTART_CONFIRM
}
